// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package mathml munder is generated from configuration file.
// Description:
package elements

import (
	"fmt"
	"time"

	"github.com/igrmk/treemap/v2"
	"github.com/samber/lo"
)

// This element is used to display an expression with an underbar.
type MathMLMUNDERElement struct {
	*Element
}

// Create a new MathMLMUNDERElement element.
// This will create a new element with the tag
// "munder" during rendering.
func MathML_MUNDER(children ...ElementRenderer) *MathMLMUNDERElement {
	e := NewElement("munder", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &MathMLMUNDERElement{Element: e}
}

func (e *MathMLMUNDERElement) Children(children ...ElementRenderer) *MathMLMUNDERElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *MathMLMUNDERElement) IfChildren(condition bool, children ...ElementRenderer) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *MathMLMUNDERElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *MathMLMUNDERElement) Attr(name string, value string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *MathMLMUNDERElement) Attrs(attrs ...string) *MathMLMUNDERElement {
	if len(attrs)%2 != 0 {
		panic("attrs must be a multiple of 2")
	}
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for i := 0; i < len(attrs); i += 2 {
		k := attrs[i]
		v := attrs[i+1]
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *MathMLMUNDERElement) AttrsMap(attrs map[string]string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for k, v := range attrs {
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *MathMLMUNDERElement) Text(text string) *MathMLMUNDERElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *MathMLMUNDERElement) TextF(format string, args ...any) *MathMLMUNDERElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *MathMLMUNDERElement) IfText(condition bool, text string) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *MathMLMUNDERElement) IfTextF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *MathMLMUNDERElement) Escaped(text string) *MathMLMUNDERElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *MathMLMUNDERElement) IfEscaped(condition bool, text string) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *MathMLMUNDERElement) EscapedF(format string, args ...any) *MathMLMUNDERElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *MathMLMUNDERElement) IfEscapedF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *MathMLMUNDERElement) CustomData(key, value string) *MathMLMUNDERElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *MathMLMUNDERElement) IfCustomData(condition bool, key, value string) *MathMLMUNDERElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *MathMLMUNDERElement) CustomDataF(key, format string, args ...any) *MathMLMUNDERElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *MathMLMUNDERElement) IfCustomDataF(condition bool, key, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *MathMLMUNDERElement) CustomDataRemove(key string) *MathMLMUNDERElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Assigns a class name or set of class names to an element
// You may assign the same class name or names to any number of elements
// If you specify multiple class names, they must be separated by whitespace
// characters.
func (e *MathMLMUNDERElement) CLASS(s ...string) *MathMLMUNDERElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Assigns a class name or set of class names to an element
// You may assign the same class name or names to any number of elements
// If you specify multiple class names, they must be separated by whitespace
// characters.
func (e *MathMLMUNDERElement) IfCLASS(condition bool, s ...string) *MathMLMUNDERElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Assigns a class name or set of class names to an element
// You may assign the same class name or names to any number of elements
// If you specify multiple class names, they must be separated by whitespace
// characters.
// Remove the attribute CLASS from the element.
func (e *MathMLMUNDERElement) CLASSRemove(s ...string) *MathMLMUNDERElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with inherent
// directionality (such as Arabic or Hebrew)
// Possible values are ltr (left-to-right) and rtl (right-to-left).
func (e *MathMLMUNDERElement) DIR(c MathMLMunderDirChoice) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dir", string(c))
	return e
}

type MathMLMunderDirChoice string

const (
	// left-to-right
	MathMLMunderDir_ltr MathMLMunderDirChoice = "ltr"
	// right-to-left
	MathMLMunderDir_rtl MathMLMunderDirChoice = "rtl"
)

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with inherent
// directionality (such as Arabic or Hebrew)
// Possible values are ltr (left-to-right) and rtl (right-to-left).
// Remove the attribute DIR from the element.
func (e *MathMLMUNDERElement) DIRRemove(c MathMLMunderDirChoice) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dir")
	return e
}

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not
// Possible values are true and false.
func (e *MathMLMUNDERElement) DISPLAYSTYLE(c MathMLMunderDisplaystyleChoice) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("displaystyle", string(c))
	return e
}

type MathMLMunderDisplaystyleChoice string

const (
	// displaystyle rules
	MathMLMunderDisplaystyle_true MathMLMunderDisplaystyleChoice = "true"
	// not displaystyle rules
	MathMLMunderDisplaystyle_false MathMLMunderDisplaystyleChoice = "false"
)

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not
// Possible values are true and false.
// Remove the attribute DISPLAYSTYLE from the element.
func (e *MathMLMUNDERElement) DISPLAYSTYLERemove(c MathMLMunderDisplaystyleChoice) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("displaystyle")
	return e
}

// This attribute assigns a name to an element
// This name must be unique in a document.
func (e *MathMLMUNDERElement) ID(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// This attribute assigns a name to an element
// This name must be unique in a document.
func (e *MathMLMUNDERElement) IDF(format string, args ...any) *MathMLMUNDERElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// This attribute assigns a name to an element
// This name must be unique in a document.
func (e *MathMLMUNDERElement) IfID(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.ID(s)
	}
	return e
}

// This attribute assigns a name to an element
// This name must be unique in a document.
func (e *MathMLMUNDERElement) IfIDF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute assigns a name to an element
// This name must be unique in a document.
// Remove the attribute ID from the element.
func (e *MathMLMUNDERElement) IDRemove(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// This attribute assigns a name to an element
// This name must be unique in a document.
func (e *MathMLMUNDERElement) IDRemoveF(format string, args ...any) *MathMLMUNDERElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHBACKGROUND(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathbackground", s)
	return e
}

// This attribute specifies the background color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHBACKGROUNDF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHBACKGROUND(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHBACKGROUND(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.MATHBACKGROUND(s)
	}
	return e
}

// This attribute specifies the background color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHBACKGROUNDF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.MATHBACKGROUND(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the background color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
// Remove the attribute MATHBACKGROUND from the element.
func (e *MathMLMUNDERElement) MATHBACKGROUNDRemove(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathbackground")
	return e
}

// This attribute specifies the background color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHBACKGROUNDRemoveF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHBACKGROUNDRemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHCOLOR(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathcolor", s)
	return e
}

// This attribute specifies the color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHCOLORF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHCOLOR(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHCOLOR(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.MATHCOLOR(s)
	}
	return e
}

// This attribute specifies the color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHCOLORF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.MATHCOLOR(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
// Remove the attribute MATHCOLOR from the element.
func (e *MathMLMUNDERElement) MATHCOLORRemove(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathcolor")
	return e
}

// This attribute specifies the color of the element
// Possible values are a color name or a color specification in the format defined
// in the CSS3 Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHCOLORRemoveF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHCOLORRemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element
// Possible values are a dimension or a dimensionless number.
func (e *MathMLMUNDERElement) MATHSIZE_STR(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathsize", s)
	return e
}

// This attribute specifies the size of the element
// Possible values are a dimension or a dimensionless number.
func (e *MathMLMUNDERElement) MATHSIZE_STRF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHSIZE_STR(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element
// Possible values are a dimension or a dimensionless number.
func (e *MathMLMUNDERElement) IfMATHSIZE_STR(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.MATHSIZE_STR(s)
	}
	return e
}

// This attribute specifies the size of the element
// Possible values are a dimension or a dimensionless number.
func (e *MathMLMUNDERElement) IfMATHSIZE_STRF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.MATHSIZE_STR(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the size of the element
// Possible values are a dimension or a dimensionless number.
// Remove the attribute MATHSIZE_STR from the element.
func (e *MathMLMUNDERElement) MATHSIZE_STRRemove(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathsize")
	return e
}

// This attribute specifies the size of the element
// Possible values are a dimension or a dimensionless number.
func (e *MathMLMUNDERElement) MATHSIZE_STRRemoveF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHSIZE_STRRemove(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should be
// used by the server processing the element’s submission, and the resulting
// resource must be delivered with a Content-Security-Policy nonce attribute
// matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) NONCE(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("nonce", s)
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should be
// used by the server processing the element’s submission, and the resulting
// resource must be delivered with a Content-Security-Policy nonce attribute
// matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) NONCEF(format string, args ...any) *MathMLMUNDERElement {
	return e.NONCE(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should be
// used by the server processing the element’s submission, and the resulting
// resource must be delivered with a Content-Security-Policy nonce attribute
// matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) IfNONCE(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.NONCE(s)
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should be
// used by the server processing the element’s submission, and the resulting
// resource must be delivered with a Content-Security-Policy nonce attribute
// matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) IfNONCEF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.NONCE(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should be
// used by the server processing the element’s submission, and the resulting
// resource must be delivered with a Content-Security-Policy nonce attribute
// matching the value of the nonce attribute.
// Remove the attribute NONCE from the element.
func (e *MathMLMUNDERElement) NONCERemove(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("nonce")
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should be
// used by the server processing the element’s submission, and the resulting
// resource must be delivered with a Content-Security-Policy nonce attribute
// matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) NONCERemoveF(format string, args ...any) *MathMLMUNDERElement {
	return e.NONCERemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the script level of the element
// Possible values are an integer between 0 and 7, inclusive.
func (e *MathMLMUNDERElement) SCRIPTLEVEL(i int) *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("scriptlevel", i)
	return e
}

// This attribute specifies the script level of the element
// Possible values are an integer between 0 and 7, inclusive.
func (e *MathMLMUNDERElement) IfSCRIPTLEVEL(condition bool, i int) *MathMLMUNDERElement {
	if condition {
		e.SCRIPTLEVEL(i)
	}
	return e
}

// This attribute specifies the script level of the element
// Possible values are an integer between 0 and 7, inclusive.
// Remove the attribute SCRIPTLEVEL from the element.
func (e *MathMLMUNDERElement) SCRIPTLEVELRemove(i int) *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("scriptlevel")
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) STYLEF(k string, format string, args ...any) *MathMLMUNDERElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) IfSTYLE(condition bool, k string, v string) *MathMLMUNDERElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) STYLE(k string, v string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) IfSTYLEF(condition bool, k string, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Add the attributes in the map to the element.
func (e *MathMLMUNDERElement) STYLEMap(m map[string]string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Add pairs of attributes to the element.
func (e *MathMLMUNDERElement) STYLEPairs(pairs ...string) *MathMLMUNDERElement {
	if len(pairs)%2 != 0 {
		panic("Must have an even number of pairs")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}

	for i := 0; i < len(pairs); i += 2 {
		kv.Add(pairs[i], pairs[i+1])
	}

	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) IfSTYLEPairs(condition bool, pairs ...string) *MathMLMUNDERElement {
	if condition {
		e.STYLEPairs(pairs...)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Remove the attribute STYLE from the element.
func (e *MathMLMUNDERElement) STYLERemove(keys ...string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document
// This value must be a number between 0 and 32767
// User agents should ignore leading zeros.
func (e *MathMLMUNDERElement) TABINDEX(i int) *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("tabindex", i)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document
// This value must be a number between 0 and 32767
// User agents should ignore leading zeros.
func (e *MathMLMUNDERElement) IfTABINDEX(condition bool, i int) *MathMLMUNDERElement {
	if condition {
		e.TABINDEX(i)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document
// This value must be a number between 0 and 32767
// User agents should ignore leading zeros.
// Remove the attribute TABINDEX from the element.
func (e *MathMLMUNDERElement) TABINDEXRemove(i int) *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("tabindex")
	return e
}

// Sets the value of any HTML attribute to an expression, and keeps it in sync.
//
// See: https://data-star.dev/reference/attributes#data-attr
func (e *MathMLMUNDERElement) DATASTAR_ATTR(key string, expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-attr%s", suffix)

	e.StringAttributes.Set(key, expression)
	return e
}

// Sets the value of any HTML attribute to an expression, and keeps it in sync.
//
// See: https://data-star.dev/reference/attributes#data-attr
func (e *MathMLMUNDERElement) IfDATASTAR_ATTR(condition bool, key string, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_ATTR(key, expression)
	}
	return e
}

// Sets the value of any HTML attribute to an expression, and keeps it in sync.
//
// See: https://data-star.dev/reference/attributes#data-attr
// Remove the attribute DATASTAR_ATTR from the element.
func (e *MathMLMUNDERElement) DATASTAR_ATTRRemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-attr" + suffix)

	return e
}

// Creates a signal (if one doesn’t already exist) and sets up two-way data
// binding between it and an element’s value.
//
// See: https://data-star.dev/reference/attributes#data-bind
func (e *MathMLMUNDERElement) DATASTAR_BIND(key string, expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-bind%s", suffix)

	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a signal (if one doesn’t already exist) and sets up two-way data
// binding between it and an element’s value.
//
// See: https://data-star.dev/reference/attributes#data-bind
func (e *MathMLMUNDERElement) IfDATASTAR_BIND(condition bool, key string, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_BIND(key, expression)
	}
	return e
}

// Creates a signal (if one doesn’t already exist) and sets up two-way data
// binding between it and an element’s value.
//
// See: https://data-star.dev/reference/attributes#data-bind
// Remove the attribute DATASTAR_BIND from the element.
func (e *MathMLMUNDERElement) DATASTAR_BINDRemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-bind" + suffix)

	return e
}

type MathMLMunderClassMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderClassModCase(
	s string,
) MathMLMunderClassMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Adds or removes a class to or from an element based on an expression.
func (e *MathMLMUNDERElement) DATASTAR_CLASS(key string, expression string, modifiers ...MathMLMunderClassMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-class%s", suffix)

	customMods := lo.Map(modifiers, func(m MathMLMunderClassMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Adds or removes a class to or from an element based on an expression.
func (e *MathMLMUNDERElement) IfDATASTAR_CLASS(condition bool, key string, expression string, modifiers ...MathMLMunderClassMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_CLASS(key, expression, modifiers...)
	}
	return e
}

// Adds or removes a class to or from an element based on an expression.
// Remove the attribute DATASTAR_CLASS from the element.
func (e *MathMLMUNDERElement) DATASTAR_CLASSRemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-class" + suffix)

	return e
}

type MathMLMunderComputedMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderComputedModCase(
	s string,
) MathMLMunderComputedMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Creates a signal that is computed based on an expression
// The computed signal is read-only, and its value is automatically updated when
// any signals in the expression are updated.
//
// See: https://data-star.dev/reference/attributes#data-computed
func (e *MathMLMUNDERElement) DATASTAR_COMPUTED(key string, expression string, modifiers ...MathMLMunderComputedMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-computed%s", suffix)

	customMods := lo.Map(modifiers, func(m MathMLMunderComputedMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a signal that is computed based on an expression
// The computed signal is read-only, and its value is automatically updated when
// any signals in the expression are updated.
//
// See: https://data-star.dev/reference/attributes#data-computed
func (e *MathMLMUNDERElement) IfDATASTAR_COMPUTED(condition bool, key string, expression string, modifiers ...MathMLMunderComputedMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_COMPUTED(key, expression, modifiers...)
	}
	return e
}

// Creates a signal that is computed based on an expression
// The computed signal is read-only, and its value is automatically updated when
// any signals in the expression are updated.
//
// See: https://data-star.dev/reference/attributes#data-computed
// Remove the attribute DATASTAR_COMPUTED from the element.
func (e *MathMLMUNDERElement) DATASTAR_COMPUTEDRemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-computed" + suffix)

	return e
}

// Executes an expression on page load and whenever any signals in the expression
// change
// This is useful for performing side effects, such as updating other signals,
// making requests to the backend, or manipulating the DOM.
//
// See: https://data-star.dev/reference/attributes#data-effect
func (e *MathMLMUNDERElement) DATASTAR_EFFECT(expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-effect"

	e.StringAttributes.Set(key, expression)
	return e
}

// Executes an expression on page load and whenever any signals in the expression
// change
// This is useful for performing side effects, such as updating other signals,
// making requests to the backend, or manipulating the DOM.
//
// See: https://data-star.dev/reference/attributes#data-effect
func (e *MathMLMUNDERElement) IfDATASTAR_EFFECT(condition bool, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_EFFECT(expression)
	}
	return e
}

// Executes an expression on page load and whenever any signals in the expression
// change
// This is useful for performing side effects, such as updating other signals,
// making requests to the backend, or manipulating the DOM.
//
// See: https://data-star.dev/reference/attributes#data-effect
// Remove the attribute DATASTAR_EFFECT from the element.
func (e *MathMLMUNDERElement) DATASTAR_EFFECTRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-effect")

	return e
}

type MathMLMunderIgnoreMod customDataKeyModifier

// Only ignore the element itself, not its descendants.
func MathMLMunderIgnoreModSelf() MathMLMunderIgnoreMod {
	return func() string {
		return "self"
	}
}

// Datastar walks the entire DOM and applies plugins to each element it encounters
// It's possible to tell Datastar to ignore an element and its descendants by
// placing a data-ignore attribute on it
// This can be useful for preventing naming conflicts with third-party libraries,
// or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore
func (e *MathMLMUNDERElement) DATASTAR_IGNORESet(b bool, modifiers ...MathMLMunderIgnoreMod) *MathMLMUNDERElement {
	key := customDataKey("data-ignore")
	customMods := lo.Map(modifiers, func(m MathMLMunderIgnoreMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(key, b)
	return e
}

// Datastar walks the entire DOM and applies plugins to each element it encounters
// It's possible to tell Datastar to ignore an element and its descendants by
// placing a data-ignore attribute on it
// This can be useful for preventing naming conflicts with third-party libraries,
// or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore
func (e *MathMLMUNDERElement) DATASTAR_IGNORE(modifiers ...MathMLMunderIgnoreMod) *MathMLMUNDERElement {
	return e.DATASTAR_IGNORESet(true, modifiers...)
}

// Similar to the data-ignore attribute, the data-ignore-morph attribute tells the
// PatchElements watcher to skip processing an element and its children when
// morphing elements
// This can be useful for preventing conflicts with third-party libraries that
// manipulate the DOM, or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore-morph
func (e *MathMLMUNDERElement) DATASTAR_IGNORE_MORPHSet(b bool) *MathMLMUNDERElement {
	key := "data-ignore-morph"
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(key, b)
	return e
}

// Similar to the data-ignore attribute, the data-ignore-morph attribute tells the
// PatchElements watcher to skip processing an element and its children when
// morphing elements
// This can be useful for preventing conflicts with third-party libraries that
// manipulate the DOM, or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore-morph
func (e *MathMLMUNDERElement) DATASTAR_IGNORE_MORPH() *MathMLMUNDERElement {
	return e.DATASTAR_IGNORE_MORPHSet(true)
}

type MathMLMunderIndicatorMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderIndicatorModCase(
	s string,
) MathMLMunderIndicatorMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Creates a signal and sets its value to true while a fetch request is in flight,
// otherwise false
// The signal can be used to show a loading indicator.
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *MathMLMUNDERElement) DATASTAR_INDICATOR(expression string, modifiers ...MathMLMunderIndicatorMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-indicator"

	customMods := lo.Map(modifiers, func(m MathMLMunderIndicatorMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a signal and sets its value to true while a fetch request is in flight,
// otherwise false
// The signal can be used to show a loading indicator.
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *MathMLMUNDERElement) IfDATASTAR_INDICATOR(condition bool, expression string, modifiers ...MathMLMunderIndicatorMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_INDICATOR(expression, modifiers...)
	}
	return e
}

// Creates a signal and sets its value to true while a fetch request is in flight,
// otherwise false
// The signal can be used to show a loading indicator.
//
// See: https://data-star.dev/reference/attributes#data-indicator
// Remove the attribute DATASTAR_INDICATOR from the element.
func (e *MathMLMUNDERElement) DATASTAR_INDICATORRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-indicator")

	return e
}

type MathMLMunderInitMod customDataKeyModifier

// Delay the event listener in milliseconds.
func MathMLMunderInitModDelayMs(
	d time.Duration,
) MathMLMunderInitMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func MathMLMunderInitModDelaySec(
	d time.Duration,
) MathMLMunderInitMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func MathMLMunderInitModViewTransition() MathMLMunderInitMod {
	return func() string {
		return "viewtransition"
	}
}

// Runs an expression when the attribute is initialized
// This can happen on page load, when an element is patched into the DOM, and any
// time the attribute is modified (via a backend action or otherwise).
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *MathMLMUNDERElement) DATASTAR_INIT(expression string, modifiers ...MathMLMunderInitMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-init"

	customMods := lo.Map(modifiers, func(m MathMLMunderInitMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression when the attribute is initialized
// This can happen on page load, when an element is patched into the DOM, and any
// time the attribute is modified (via a backend action or otherwise).
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *MathMLMUNDERElement) IfDATASTAR_INIT(condition bool, expression string, modifiers ...MathMLMunderInitMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_INIT(expression, modifiers...)
	}
	return e
}

// Runs an expression when the attribute is initialized
// This can happen on page load, when an element is patched into the DOM, and any
// time the attribute is modified (via a backend action or otherwise).
//
// See: https://data-star.dev/reference/attributes#data-indicator
// Remove the attribute DATASTAR_INIT from the element.
func (e *MathMLMUNDERElement) DATASTAR_INITRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-init")

	return e
}

type MathMLMunderJsonSignalsMod customDataKeyModifier

// Outputs a more compact JSON format without extra whitespace
// Useful for displaying filtered data inline.
func MathMLMunderJsonSignalsModTerse() MathMLMunderJsonSignalsMod {
	return func() string {
		return "terse"
	}
}

// Sets the text content of an element to a reactive JSON stringified version of
// signals
// Useful when troubleshooting an issue.
//
// See: https://data-star.dev/reference/attributes#data-json-signals
func (e *MathMLMUNDERElement) DATASTAR_JSON_SIGNALS(expression string, modifiers ...MathMLMunderJsonSignalsMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-json-signals"

	customMods := lo.Map(modifiers, func(m MathMLMunderJsonSignalsMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Sets the text content of an element to a reactive JSON stringified version of
// signals
// Useful when troubleshooting an issue.
//
// See: https://data-star.dev/reference/attributes#data-json-signals
func (e *MathMLMUNDERElement) IfDATASTAR_JSON_SIGNALS(condition bool, expression string, modifiers ...MathMLMunderJsonSignalsMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_JSON_SIGNALS(expression, modifiers...)
	}
	return e
}

// Sets the text content of an element to a reactive JSON stringified version of
// signals
// Useful when troubleshooting an issue.
//
// See: https://data-star.dev/reference/attributes#data-json-signals
// Remove the attribute DATASTAR_JSON_SIGNALS from the element.
func (e *MathMLMUNDERElement) DATASTAR_JSON_SIGNALSRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-json-signals")

	return e
}

type MathMLMunderOnMod customDataKeyModifier

// Only run the expression once
// Only works with built-in events.
func MathMLMunderOnModOnce() MathMLMunderOnMod {
	return func() string {
		return "once"
	}
}

// Do not call preventDefault on the event listener
// Only works with built-in events.
func MathMLMunderOnModPassive() MathMLMunderOnMod {
	return func() string {
		return "passive"
	}
}

// Use capture event listener
// Only works with built-in events.
func MathMLMunderOnModCapture() MathMLMunderOnMod {
	return func() string {
		return "capture"
	}
}

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderOnModCase(
	s string,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Delay the event listener in milliseconds.
func MathMLMunderOnModDelayMs(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func MathMLMunderOnModDelaySec(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Debounces the event handler
func MathMLMunderOnModDebounceMs(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds with leading edge.
func MathMLMunderOnModDebounceMsLeading(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.leading", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds without trailing edge.
func MathMLMunderOnModDebounceMsNoTrailing(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.notrailing", d.Milliseconds())
	}
}

// Debounces the event handler
func MathMLMunderOnModDebounceSec(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds with leading edge.
func MathMLMunderOnModDebounceSecLeading(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.leading", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds without trailing edge.
func MathMLMunderOnModDebounceSecNoTrailing(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.notrailing", int(d.Seconds()))
	}
}

// Throttles the event handler
func MathMLMunderOnModThrottleMs(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds without leading edge.
func MathMLMunderOnModThrottleMsNoLeading(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.noleading", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds with trailing edge.
func MathMLMunderOnModThrottleMsTrailing(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.trailing", d.Milliseconds())
	}
}

// Throttles the event listener in seconds.
func MathMLMunderOnModThrottleSec(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds without leading edge.
func MathMLMunderOnModThrottleSecNoLeading(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.noleading", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds with trailing edge.
func MathMLMunderOnModThrottleSecTrailing(
	d time.Duration,
) MathMLMunderOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.trailing", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func MathMLMunderOnModViewTransition() MathMLMunderOnMod {
	return func() string {
		return "viewtransition"
	}
}

// Attaches the event listener to the 'window' element.
func MathMLMunderOnModWindow() MathMLMunderOnMod {
	return func() string {
		return "window"
	}
}

// Calls 'preventDefault' on the event listener.
func MathMLMunderOnModPrevent() MathMLMunderOnMod {
	return func() string {
		return "prevent"
	}
}

// Triggers when the event is outside the element.
func MathMLMunderOnModOutside() MathMLMunderOnMod {
	return func() string {
		return "outside"
	}
}

// Calls 'stopPropagation' on the event listener.
func MathMLMunderOnModStop() MathMLMunderOnMod {
	return func() string {
		return "stop"
	}
}

// Attaches an event listener to an element, executing an expression whenever the
// event is triggered.
//
// See: https://data-star.dev/reference/attributes#data-on
func (e *MathMLMUNDERElement) DATASTAR_ON(key string, expression string, modifiers ...MathMLMunderOnMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-on%s", suffix)

	customMods := lo.Map(modifiers, func(m MathMLMunderOnMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Attaches an event listener to an element, executing an expression whenever the
// event is triggered.
//
// See: https://data-star.dev/reference/attributes#data-on
func (e *MathMLMUNDERElement) IfDATASTAR_ON(condition bool, key string, expression string, modifiers ...MathMLMunderOnMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_ON(key, expression, modifiers...)
	}
	return e
}

// Attaches an event listener to an element, executing an expression whenever the
// event is triggered.
//
// See: https://data-star.dev/reference/attributes#data-on
// Remove the attribute DATASTAR_ON from the element.
func (e *MathMLMUNDERElement) DATASTAR_ONRemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-on" + suffix)

	return e
}

type MathMLMunderOnIntersectMod customDataKeyModifier

// Only run the expression once
// Only works with built-in events.
func MathMLMunderOnIntersectModOnce() MathMLMunderOnIntersectMod {
	return func() string {
		return "once"
	}
}

// Trigger when half of the element is visible.
func MathMLMunderOnIntersectModHalf() MathMLMunderOnIntersectMod {
	return func() string {
		return "half"
	}
}

// Trigger when the full element is visible.
func MathMLMunderOnIntersectModFull() MathMLMunderOnIntersectMod {
	return func() string {
		return "full"
	}
}

// Delay the event listener in milliseconds.
func MathMLMunderOnIntersectModDelayMs(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func MathMLMunderOnIntersectModDelaySec(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Debounces the event handler
func MathMLMunderOnIntersectModDebounceMs(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds with leading edge.
func MathMLMunderOnIntersectModDebounceMsLeading(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.leading", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds without trailing edge.
func MathMLMunderOnIntersectModDebounceMsNoTrailing(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.notrailing", d.Milliseconds())
	}
}

// Debounces the event handler
func MathMLMunderOnIntersectModDebounceSec(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds with leading edge.
func MathMLMunderOnIntersectModDebounceSecLeading(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.leading", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds without trailing edge.
func MathMLMunderOnIntersectModDebounceSecNoTrailing(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.notrailing", int(d.Seconds()))
	}
}

// Throttles the event handler
func MathMLMunderOnIntersectModThrottleMs(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds without leading edge.
func MathMLMunderOnIntersectModThrottleMsNoLeading(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.noleading", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds with trailing edge.
func MathMLMunderOnIntersectModThrottleMsTrailing(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.trailing", d.Milliseconds())
	}
}

// Throttles the event listener in seconds.
func MathMLMunderOnIntersectModThrottleSec(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds without leading edge.
func MathMLMunderOnIntersectModThrottleSecNoLeading(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.noleading", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds with trailing edge.
func MathMLMunderOnIntersectModThrottleSecTrailing(
	d time.Duration,
) MathMLMunderOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.trailing", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func MathMLMunderOnIntersectModViewTransition() MathMLMunderOnIntersectMod {
	return func() string {
		return "viewtransition"
	}
}

// Runs an expression when the element intersects with the viewport.
func (e *MathMLMUNDERElement) DATASTAR_ON_INTERSECT(expression string, modifiers ...MathMLMunderOnIntersectMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-intersect"

	customMods := lo.Map(modifiers, func(m MathMLMunderOnIntersectMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression when the element intersects with the viewport.
func (e *MathMLMUNDERElement) IfDATASTAR_ON_INTERSECT(condition bool, expression string, modifiers ...MathMLMunderOnIntersectMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_ON_INTERSECT(expression, modifiers...)
	}
	return e
}

// Runs an expression when the element intersects with the viewport.
// Remove the attribute DATASTAR_ON_INTERSECT from the element.
func (e *MathMLMUNDERElement) DATASTAR_ON_INTERSECTRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-intersect")

	return e
}

type MathMLMunderOnIntervalMod customDataKeyModifier

// Sets the interval duration in milliseconds.
func MathMLMunderOnIntervalModDurationMs(
	d time.Duration,
) MathMLMunderOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%dms", d.Milliseconds())
	}
}

// Sets the interval duration in milliseconds
// Execute the first interval immediately.
func MathMLMunderOnIntervalModDurationMsLeading(
	d time.Duration,
) MathMLMunderOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%dms.leading", d.Milliseconds())
	}
}

// Sets the interval duration in seconds.
func MathMLMunderOnIntervalModDurationSec(
	d time.Duration,
) MathMLMunderOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%ds", int(d.Seconds()))
	}
}

// Sets the interval duration in seconds
// Execute the first interval immediately.
func MathMLMunderOnIntervalModDurationSecLeading(
	d time.Duration,
) MathMLMunderOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%ds.leading", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func MathMLMunderOnIntervalModViewTransition() MathMLMunderOnIntervalMod {
	return func() string {
		return "viewtransition"
	}
}

// Runs an expression at a regular interval
// The interval duration defaults to one second and can be modified using the
// '__duration' modifier.
//
// See: https://data-star.dev/reference/attributes#data-on-interval
func (e *MathMLMUNDERElement) DATASTAR_ON_INTERVAL(expression string, modifiers ...MathMLMunderOnIntervalMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-interval"

	customMods := lo.Map(modifiers, func(m MathMLMunderOnIntervalMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression at a regular interval
// The interval duration defaults to one second and can be modified using the
// '__duration' modifier.
//
// See: https://data-star.dev/reference/attributes#data-on-interval
func (e *MathMLMUNDERElement) IfDATASTAR_ON_INTERVAL(condition bool, expression string, modifiers ...MathMLMunderOnIntervalMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_ON_INTERVAL(expression, modifiers...)
	}
	return e
}

// Runs an expression at a regular interval
// The interval duration defaults to one second and can be modified using the
// '__duration' modifier.
//
// See: https://data-star.dev/reference/attributes#data-on-interval
// Remove the attribute DATASTAR_ON_INTERVAL from the element.
func (e *MathMLMUNDERElement) DATASTAR_ON_INTERVALRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-interval")

	return e
}

type MathMLMunderOnSignalPatchMod customDataKeyModifier

// Delay the event listener in milliseconds.
func MathMLMunderOnSignalPatchModDelayMs(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func MathMLMunderOnSignalPatchModDelaySec(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Debounces the event handler
func MathMLMunderOnSignalPatchModDebounceMs(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds with leading edge.
func MathMLMunderOnSignalPatchModDebounceMsLeading(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.leading", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds without trailing edge.
func MathMLMunderOnSignalPatchModDebounceMsNoTrailing(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.notrailing", d.Milliseconds())
	}
}

// Debounces the event handler
func MathMLMunderOnSignalPatchModDebounceSec(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds with leading edge.
func MathMLMunderOnSignalPatchModDebounceSecLeading(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.leading", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds without trailing edge.
func MathMLMunderOnSignalPatchModDebounceSecNoTrailing(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.notrailing", int(d.Seconds()))
	}
}

// Throttles the event handler
func MathMLMunderOnSignalPatchModThrottleMs(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds without leading edge.
func MathMLMunderOnSignalPatchModThrottleMsNoLeading(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.noleading", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds with trailing edge.
func MathMLMunderOnSignalPatchModThrottleMsTrailing(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.trailing", d.Milliseconds())
	}
}

// Throttles the event listener in seconds.
func MathMLMunderOnSignalPatchModThrottleSec(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds without leading edge.
func MathMLMunderOnSignalPatchModThrottleSecNoLeading(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.noleading", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds with trailing edge.
func MathMLMunderOnSignalPatchModThrottleSecTrailing(
	d time.Duration,
) MathMLMunderOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.trailing", int(d.Seconds()))
	}
}

// Runs an expression whenever any signals are patched
// This is useful for tracking changes, updating computed values, or triggering
// side effects when data updates.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch
func (e *MathMLMUNDERElement) DATASTAR_ON_SIGNAL_PATCH(expression string, modifiers ...MathMLMunderOnSignalPatchMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-signal-patch"

	customMods := lo.Map(modifiers, func(m MathMLMunderOnSignalPatchMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression whenever any signals are patched
// This is useful for tracking changes, updating computed values, or triggering
// side effects when data updates.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch
func (e *MathMLMUNDERElement) IfDATASTAR_ON_SIGNAL_PATCH(condition bool, expression string, modifiers ...MathMLMunderOnSignalPatchMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_ON_SIGNAL_PATCH(expression, modifiers...)
	}
	return e
}

// Runs an expression whenever any signals are patched
// This is useful for tracking changes, updating computed values, or triggering
// side effects when data updates.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch
// Remove the attribute DATASTAR_ON_SIGNAL_PATCH from the element.
func (e *MathMLMUNDERElement) DATASTAR_ON_SIGNAL_PATCHRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-signal-patch")

	return e
}

// Filters which signals to watch when using the data-on-signal-patch attribute.
//
// The data-on-signal-patch-filter attribute accepts an object with include and/or
// exclude properties that are regular expressions.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch-filter
func (e *MathMLMUNDERElement) DATASTAR_ON_SIGNAL_PATCH_FILTER(expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-signal-patch-filter"

	e.StringAttributes.Set(key, expression)
	return e
}

// Filters which signals to watch when using the data-on-signal-patch attribute.
//
// The data-on-signal-patch-filter attribute accepts an object with include and/or
// exclude properties that are regular expressions.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch-filter
func (e *MathMLMUNDERElement) IfDATASTAR_ON_SIGNAL_PATCH_FILTER(condition bool, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_ON_SIGNAL_PATCH_FILTER(expression)
	}
	return e
}

// Filters which signals to watch when using the data-on-signal-patch attribute.
//
// The data-on-signal-patch-filter attribute accepts an object with include and/or
// exclude properties that are regular expressions.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch-filter
// Remove the attribute DATASTAR_ON_SIGNAL_PATCH_FILTER from the element.
func (e *MathMLMUNDERElement) DATASTAR_ON_SIGNAL_PATCH_FILTERRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-signal-patch-filter")

	return e
}

// Preserves the value of an attribute when morphing DOM elements.
//
// See: https://data-star.dev/reference/attributes#data-preserve-attr
func (e *MathMLMUNDERElement) DATASTAR_PRESERVE_ATTR(expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-preserve-attr"

	e.StringAttributes.Set(key, expression)
	return e
}

// Preserves the value of an attribute when morphing DOM elements.
//
// See: https://data-star.dev/reference/attributes#data-preserve-attr
func (e *MathMLMUNDERElement) IfDATASTAR_PRESERVE_ATTR(condition bool, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_PRESERVE_ATTR(expression)
	}
	return e
}

// Preserves the value of an attribute when morphing DOM elements.
//
// See: https://data-star.dev/reference/attributes#data-preserve-attr
// Remove the attribute DATASTAR_PRESERVE_ATTR from the element.
func (e *MathMLMUNDERElement) DATASTAR_PRESERVE_ATTRRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-preserve-attr")

	return e
}

type MathMLMunderRefMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderRefModCase(
	s string,
) MathMLMunderRefMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Creates a new signal that is a reference to the element on which the data
// attribute is placed.
//
// See: https://data-star.dev/reference/attributes#data-ref
func (e *MathMLMUNDERElement) DATASTAR_REF(expression string, modifiers ...MathMLMunderRefMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-ref"

	customMods := lo.Map(modifiers, func(m MathMLMunderRefMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a new signal that is a reference to the element on which the data
// attribute is placed.
//
// See: https://data-star.dev/reference/attributes#data-ref
func (e *MathMLMUNDERElement) IfDATASTAR_REF(condition bool, expression string, modifiers ...MathMLMunderRefMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_REF(expression, modifiers...)
	}
	return e
}

// Creates a new signal that is a reference to the element on which the data
// attribute is placed.
//
// See: https://data-star.dev/reference/attributes#data-ref
// Remove the attribute DATASTAR_REF from the element.
func (e *MathMLMUNDERElement) DATASTAR_REFRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-ref")

	return e
}

// Shows or hides an element based on whether an expression evaluates to 'true' or
// 'false'
// For anything with custom requirements, use 'data-class' instead.
//
// See: https://data-star.dev/reference/attributes#data-show
func (e *MathMLMUNDERElement) DATASTAR_SHOW(expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-show"

	e.StringAttributes.Set(key, expression)
	return e
}

// Shows or hides an element based on whether an expression evaluates to 'true' or
// 'false'
// For anything with custom requirements, use 'data-class' instead.
//
// See: https://data-star.dev/reference/attributes#data-show
func (e *MathMLMUNDERElement) IfDATASTAR_SHOW(condition bool, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_SHOW(expression)
	}
	return e
}

// Shows or hides an element based on whether an expression evaluates to 'true' or
// 'false'
// For anything with custom requirements, use 'data-class' instead.
//
// See: https://data-star.dev/reference/attributes#data-show
// Remove the attribute DATASTAR_SHOW from the element.
func (e *MathMLMUNDERElement) DATASTAR_SHOWRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-show")

	return e
}

type MathMLMunderSignalsMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderSignalsModCase(
	s string,
) MathMLMunderSignalsMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Only patches signals if their keys do not already exist
// This is useful for setting defaults without overwriting existing values.
func MathMLMunderSignalsModIfMissing() MathMLMunderSignalsMod {
	return func() string {
		return "ifmissing"
	}
}

// Patches (adds, updates or removes) one or more signals into the existing
// signals
// Values defined later in the DOM tree override those defined earlier.
//
// See: https://data-star.dev/reference/attributes#data-signals
func (e *MathMLMUNDERElement) DATASTAR_SIGNALS(key string, expression string, modifiers ...MathMLMunderSignalsMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-signals%s", suffix)

	customMods := lo.Map(modifiers, func(m MathMLMunderSignalsMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Patches (adds, updates or removes) one or more signals into the existing
// signals
// Values defined later in the DOM tree override those defined earlier.
//
// See: https://data-star.dev/reference/attributes#data-signals
func (e *MathMLMUNDERElement) IfDATASTAR_SIGNALS(condition bool, key string, expression string, modifiers ...MathMLMunderSignalsMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_SIGNALS(key, expression, modifiers...)
	}
	return e
}

// Patches (adds, updates or removes) one or more signals into the existing
// signals
// Values defined later in the DOM tree override those defined earlier.
//
// See: https://data-star.dev/reference/attributes#data-signals
// Remove the attribute DATASTAR_SIGNALS from the element.
func (e *MathMLMUNDERElement) DATASTAR_SIGNALSRemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-signals" + suffix)

	return e
}

type MathMLMunderStyleMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func MathMLMunderStyleModCase(
	s string,
) MathMLMunderStyleMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Sets the value of inline CSS styles on an element based on an expression, and
// keeps them in sync.
//
// See: https://data-star.dev/reference/attributes#data-style
func (e *MathMLMUNDERElement) DATASTAR_STYLE(key string, expression string, modifiers ...MathMLMunderStyleMod) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-style%s", suffix)

	customMods := lo.Map(modifiers, func(m MathMLMunderStyleMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Sets the value of inline CSS styles on an element based on an expression, and
// keeps them in sync.
//
// See: https://data-star.dev/reference/attributes#data-style
func (e *MathMLMUNDERElement) IfDATASTAR_STYLE(condition bool, key string, expression string, modifiers ...MathMLMunderStyleMod) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_STYLE(key, expression, modifiers...)
	}
	return e
}

// Sets the value of inline CSS styles on an element based on an expression, and
// keeps them in sync.
//
// See: https://data-star.dev/reference/attributes#data-style
// Remove the attribute DATASTAR_STYLE from the element.
func (e *MathMLMUNDERElement) DATASTAR_STYLERemove(key string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-style" + suffix)

	return e
}

// Binds the text content of an element to an expression.
//
// See: https://data-star.dev/reference/attributes#data-text
func (e *MathMLMUNDERElement) DATASTAR_TEXT(expression string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-text"

	e.StringAttributes.Set(key, expression)
	return e
}

// Binds the text content of an element to an expression.
//
// See: https://data-star.dev/reference/attributes#data-text
func (e *MathMLMUNDERElement) IfDATASTAR_TEXT(condition bool, expression string) *MathMLMUNDERElement {
	if condition {
		e.DATASTAR_TEXT(expression)
	}
	return e
}

// Binds the text content of an element to an expression.
//
// See: https://data-star.dev/reference/attributes#data-text
// Remove the attribute DATASTAR_TEXT from the element.
func (e *MathMLMUNDERElement) DATASTAR_TEXTRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-text")

	return e
}
