// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg radialGradient is generated from configuration file.
// Description:
package elements

import (
	"fmt"
	"time"

	"github.com/igrmk/treemap/v2"
	"github.com/samber/lo"
)

// The <radialGradient> SVG element lets authors define radial gradients to fill
// or stroke graphical elements.
type SVGRADIALGRADIENTElement struct {
	*Element
}

// Create a new SVGRADIALGRADIENTElement element.
// This will create a new element with the tag
// "radialGradient" during rendering.
func SVG_RADIALGRADIENT(children ...ElementRenderer) *SVGRADIALGRADIENTElement {
	e := NewElement("radialGradient", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGRADIALGRADIENTElement{Element: e}
}

func (e *SVGRADIALGRADIENTElement) Children(children ...ElementRenderer) *SVGRADIALGRADIENTElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGRADIALGRADIENTElement) IfChildren(condition bool, children ...ElementRenderer) *SVGRADIALGRADIENTElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGRADIALGRADIENTElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) Attr(name string, value string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGRADIALGRADIENTElement) Attrs(attrs ...string) *SVGRADIALGRADIENTElement {
	if len(attrs)%2 != 0 {
		panic("attrs must be a multiple of 2")
	}
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for i := 0; i < len(attrs); i += 2 {
		k := attrs[i]
		v := attrs[i+1]
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) AttrsMap(attrs map[string]string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for k, v := range attrs {
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) Text(text string) *SVGRADIALGRADIENTElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGRADIALGRADIENTElement) TextF(format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGRADIALGRADIENTElement) IfText(condition bool, text string) *SVGRADIALGRADIENTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) IfTextF(condition bool, format string, args ...any) *SVGRADIALGRADIENTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) Escaped(text string) *SVGRADIALGRADIENTElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGRADIALGRADIENTElement) IfEscaped(condition bool, text string) *SVGRADIALGRADIENTElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) EscapedF(format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGRADIALGRADIENTElement) IfEscapedF(condition bool, format string, args ...any) *SVGRADIALGRADIENTElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) CustomData(key, value string) *SVGRADIALGRADIENTElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGRADIALGRADIENTElement) IfCustomData(condition bool, key, value string) *SVGRADIALGRADIENTElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) CustomDataF(key, format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGRADIALGRADIENTElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGRADIALGRADIENTElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGRADIALGRADIENTElement) CustomDataRemove(key string) *SVGRADIALGRADIENTElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The coordinate system for attributes cx, cy and r.
func (e *SVGRADIALGRADIENTElement) GRADIENT_UNITS(c SVGRadialGradientGradientUnitsChoice) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("gradientUnits", string(c))
	return e
}

type SVGRadialGradientGradientUnitsChoice string

const (
	// The coordinate system for attributes cx, cy and r.
	SVGRadialGradientGradientUnits_userSpaceOnUse SVGRadialGradientGradientUnitsChoice = "userSpaceOnUse"
	// The coordinate system for attributes cx, cy and r.
	SVGRadialGradientGradientUnits_objectBoundingBox SVGRadialGradientGradientUnitsChoice = "objectBoundingBox"
)

// The coordinate system for attributes cx, cy and r.
// Remove the attribute GRADIENT_UNITS from the element.
func (e *SVGRADIALGRADIENTElement) GRADIENT_UNITSRemove(c SVGRadialGradientGradientUnitsChoice) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("gradientUnits")
	return e
}

// The definition of how the gradient is applied, read about <a
// href="https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform">gradientTransform</a>.
func (e *SVGRADIALGRADIENTElement) GRADIENT_TRANSFORM(s string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("gradientTransform", s)
	return e
}

// The definition of how the gradient is applied, read about <a
// href="https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform">gradientTransform</a>.
func (e *SVGRADIALGRADIENTElement) GRADIENT_TRANSFORMF(format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.GRADIENT_TRANSFORM(fmt.Sprintf(format, args...))
}

// The definition of how the gradient is applied, read about <a
// href="https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform">gradientTransform</a>.
func (e *SVGRADIALGRADIENTElement) IfGRADIENT_TRANSFORM(condition bool, s string) *SVGRADIALGRADIENTElement {
	if condition {
		e.GRADIENT_TRANSFORM(s)
	}
	return e
}

// The definition of how the gradient is applied, read about <a
// href="https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform">gradientTransform</a>.
func (e *SVGRADIALGRADIENTElement) IfGRADIENT_TRANSFORMF(condition bool, format string, args ...any) *SVGRADIALGRADIENTElement {
	if condition {
		e.GRADIENT_TRANSFORM(fmt.Sprintf(format, args...))
	}
	return e
}

// The definition of how the gradient is applied, read about <a
// href="https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform">gradientTransform</a>.
// Remove the attribute GRADIENT_TRANSFORM from the element.
func (e *SVGRADIALGRADIENTElement) GRADIENT_TRANSFORMRemove(s string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("gradientTransform")
	return e
}

// The definition of how the gradient is applied, read about <a
// href="https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform">gradientTransform</a>.
func (e *SVGRADIALGRADIENTElement) GRADIENT_TRANSFORMRemoveF(format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.GRADIENT_TRANSFORMRemove(fmt.Sprintf(format, args...))
}

// The x-axis coordinate of the largest (i.e., outermost) circle for the radial
// gradient.
func (e *SVGRADIALGRADIENTElement) CX(f float64) *SVGRADIALGRADIENTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("cx", f)
	return e
}

// The x-axis coordinate of the largest (i.e., outermost) circle for the radial
// gradient.
func (e *SVGRADIALGRADIENTElement) IfCX(condition bool, f float64) *SVGRADIALGRADIENTElement {
	if condition {
		e.CX(f)
	}
	return e
}

// The y-axis coordinate of the largest (i.e., outermost) circle for the radial
// gradient.
func (e *SVGRADIALGRADIENTElement) CY(f float64) *SVGRADIALGRADIENTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("cy", f)
	return e
}

// The y-axis coordinate of the largest (i.e., outermost) circle for the radial
// gradient.
func (e *SVGRADIALGRADIENTElement) IfCY(condition bool, f float64) *SVGRADIALGRADIENTElement {
	if condition {
		e.CY(f)
	}
	return e
}

// The radius of the largest (i.e., outermost) circle for the radial gradient.
func (e *SVGRADIALGRADIENTElement) R(f float64) *SVGRADIALGRADIENTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("r", f)
	return e
}

// The radius of the largest (i.e., outermost) circle for the radial gradient.
func (e *SVGRADIALGRADIENTElement) IfR(condition bool, f float64) *SVGRADIALGRADIENTElement {
	if condition {
		e.R(f)
	}
	return e
}

// The x-axis coordinate of the point at which the focal point of the radial
// gradient is placed.
func (e *SVGRADIALGRADIENTElement) FX(f float64) *SVGRADIALGRADIENTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("fx", f)
	return e
}

// The x-axis coordinate of the point at which the focal point of the radial
// gradient is placed.
func (e *SVGRADIALGRADIENTElement) IfFX(condition bool, f float64) *SVGRADIALGRADIENTElement {
	if condition {
		e.FX(f)
	}
	return e
}

// The y-axis coordinate of the point at which the focal point of the radial
// gradient is placed.
func (e *SVGRADIALGRADIENTElement) FY(f float64) *SVGRADIALGRADIENTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("fy", f)
	return e
}

// The y-axis coordinate of the point at which the focal point of the radial
// gradient is placed.
func (e *SVGRADIALGRADIENTElement) IfFY(condition bool, f float64) *SVGRADIALGRADIENTElement {
	if condition {
		e.FY(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGRADIALGRADIENTElement) ID(s string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGRADIALGRADIENTElement) IDF(format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGRADIALGRADIENTElement) IfID(condition bool, s string) *SVGRADIALGRADIENTElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGRADIALGRADIENTElement) IfIDF(condition bool, format string, args ...any) *SVGRADIALGRADIENTElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGRADIALGRADIENTElement) IDRemove(s string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGRADIALGRADIENTElement) IDRemoveF(format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGRADIALGRADIENTElement) CLASS(s ...string) *SVGRADIALGRADIENTElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGRADIALGRADIENTElement) IfCLASS(condition bool, s ...string) *SVGRADIALGRADIENTElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGRADIALGRADIENTElement) CLASSRemove(s ...string) *SVGRADIALGRADIENTElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRADIALGRADIENTElement) STYLEF(k string, format string, args ...any) *SVGRADIALGRADIENTElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGRADIALGRADIENTElement) IfSTYLE(condition bool, k string, v string) *SVGRADIALGRADIENTElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRADIALGRADIENTElement) STYLE(k string, v string) *SVGRADIALGRADIENTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRADIALGRADIENTElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGRADIALGRADIENTElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGRADIALGRADIENTElement) STYLEMap(m map[string]string) *SVGRADIALGRADIENTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add pairs of attributes to the element.
func (e *SVGRADIALGRADIENTElement) STYLEPairs(pairs ...string) *SVGRADIALGRADIENTElement {
	if len(pairs)%2 != 0 {
		panic("Must have an even number of pairs")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}

	for i := 0; i < len(pairs); i += 2 {
		kv.Add(pairs[i], pairs[i+1])
	}

	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRADIALGRADIENTElement) IfSTYLEPairs(condition bool, pairs ...string) *SVGRADIALGRADIENTElement {
	if condition {
		e.STYLEPairs(pairs...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGRADIALGRADIENTElement) STYLERemove(keys ...string) *SVGRADIALGRADIENTElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}

// Sets the value of any HTML attribute to an expression, and keeps it in sync.
//
// See: https://data-star.dev/reference/attributes#data-attr
func (e *SVGRADIALGRADIENTElement) DATASTAR_ATTR(key string, expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-attr%s", suffix)

	e.StringAttributes.Set(key, expression)
	return e
}

// Sets the value of any HTML attribute to an expression, and keeps it in sync.
//
// See: https://data-star.dev/reference/attributes#data-attr
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_ATTR(condition bool, key string, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_ATTR(key, expression)
	}
	return e
}

// Sets the value of any HTML attribute to an expression, and keeps it in sync.
//
// See: https://data-star.dev/reference/attributes#data-attr
// Remove the attribute DATASTAR_ATTR from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ATTRRemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-attr" + suffix)

	return e
}

// Creates a signal (if one doesn’t already exist) and sets up two-way data
// binding between it and an element’s value.
//
// See: https://data-star.dev/reference/attributes#data-bind
func (e *SVGRADIALGRADIENTElement) DATASTAR_BIND(key string, expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-bind%s", suffix)

	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a signal (if one doesn’t already exist) and sets up two-way data
// binding between it and an element’s value.
//
// See: https://data-star.dev/reference/attributes#data-bind
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_BIND(condition bool, key string, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_BIND(key, expression)
	}
	return e
}

// Creates a signal (if one doesn’t already exist) and sets up two-way data
// binding between it and an element’s value.
//
// See: https://data-star.dev/reference/attributes#data-bind
// Remove the attribute DATASTAR_BIND from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_BINDRemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-bind" + suffix)

	return e
}

type SVGRadialGradientClassMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientClassModCase(
	s string,
) SVGRadialGradientClassMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Adds or removes a class to or from an element based on an expression.
func (e *SVGRADIALGRADIENTElement) DATASTAR_CLASS(key string, expression string, modifiers ...SVGRadialGradientClassMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-class%s", suffix)

	customMods := lo.Map(modifiers, func(m SVGRadialGradientClassMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Adds or removes a class to or from an element based on an expression.
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_CLASS(condition bool, key string, expression string, modifiers ...SVGRadialGradientClassMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_CLASS(key, expression, modifiers...)
	}
	return e
}

// Adds or removes a class to or from an element based on an expression.
// Remove the attribute DATASTAR_CLASS from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_CLASSRemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-class" + suffix)

	return e
}

type SVGRadialGradientComputedMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientComputedModCase(
	s string,
) SVGRadialGradientComputedMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Creates a signal that is computed based on an expression
// The computed signal is read-only, and its value is automatically updated when
// any signals in the expression are updated.
//
// See: https://data-star.dev/reference/attributes#data-computed
func (e *SVGRADIALGRADIENTElement) DATASTAR_COMPUTED(key string, expression string, modifiers ...SVGRadialGradientComputedMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-computed%s", suffix)

	customMods := lo.Map(modifiers, func(m SVGRadialGradientComputedMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a signal that is computed based on an expression
// The computed signal is read-only, and its value is automatically updated when
// any signals in the expression are updated.
//
// See: https://data-star.dev/reference/attributes#data-computed
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_COMPUTED(condition bool, key string, expression string, modifiers ...SVGRadialGradientComputedMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_COMPUTED(key, expression, modifiers...)
	}
	return e
}

// Creates a signal that is computed based on an expression
// The computed signal is read-only, and its value is automatically updated when
// any signals in the expression are updated.
//
// See: https://data-star.dev/reference/attributes#data-computed
// Remove the attribute DATASTAR_COMPUTED from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_COMPUTEDRemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-computed" + suffix)

	return e
}

// Executes an expression on page load and whenever any signals in the expression
// change
// This is useful for performing side effects, such as updating other signals,
// making requests to the backend, or manipulating the DOM.
//
// See: https://data-star.dev/reference/attributes#data-effect
func (e *SVGRADIALGRADIENTElement) DATASTAR_EFFECT(expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-effect"

	e.StringAttributes.Set(key, expression)
	return e
}

// Executes an expression on page load and whenever any signals in the expression
// change
// This is useful for performing side effects, such as updating other signals,
// making requests to the backend, or manipulating the DOM.
//
// See: https://data-star.dev/reference/attributes#data-effect
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_EFFECT(condition bool, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_EFFECT(expression)
	}
	return e
}

// Executes an expression on page load and whenever any signals in the expression
// change
// This is useful for performing side effects, such as updating other signals,
// making requests to the backend, or manipulating the DOM.
//
// See: https://data-star.dev/reference/attributes#data-effect
// Remove the attribute DATASTAR_EFFECT from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_EFFECTRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-effect")

	return e
}

type SVGRadialGradientIgnoreMod customDataKeyModifier

// Only ignore the element itself, not its descendants.
func SVGRadialGradientIgnoreModSelf() SVGRadialGradientIgnoreMod {
	return func() string {
		return "self"
	}
}

// Datastar walks the entire DOM and applies plugins to each element it encounters
// It's possible to tell Datastar to ignore an element and its descendants by
// placing a data-ignore attribute on it
// This can be useful for preventing naming conflicts with third-party libraries,
// or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore
func (e *SVGRADIALGRADIENTElement) DATASTAR_IGNORESet(b bool, modifiers ...SVGRadialGradientIgnoreMod) *SVGRADIALGRADIENTElement {
	key := customDataKey("data-ignore")
	customMods := lo.Map(modifiers, func(m SVGRadialGradientIgnoreMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(key, b)
	return e
}

// Datastar walks the entire DOM and applies plugins to each element it encounters
// It's possible to tell Datastar to ignore an element and its descendants by
// placing a data-ignore attribute on it
// This can be useful for preventing naming conflicts with third-party libraries,
// or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore
func (e *SVGRADIALGRADIENTElement) DATASTAR_IGNORE(modifiers ...SVGRadialGradientIgnoreMod) *SVGRADIALGRADIENTElement {
	return e.DATASTAR_IGNORESet(true, modifiers...)
}

// Similar to the data-ignore attribute, the data-ignore-morph attribute tells the
// PatchElements watcher to skip processing an element and its children when
// morphing elements
// This can be useful for preventing conflicts with third-party libraries that
// manipulate the DOM, or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore-morph
func (e *SVGRADIALGRADIENTElement) DATASTAR_IGNORE_MORPHSet(b bool) *SVGRADIALGRADIENTElement {
	key := "data-ignore-morph"
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(key, b)
	return e
}

// Similar to the data-ignore attribute, the data-ignore-morph attribute tells the
// PatchElements watcher to skip processing an element and its children when
// morphing elements
// This can be useful for preventing conflicts with third-party libraries that
// manipulate the DOM, or when you are unable to escape user input.
//
// See: https://data-star.dev/reference/attributes#data-ignore-morph
func (e *SVGRADIALGRADIENTElement) DATASTAR_IGNORE_MORPH() *SVGRADIALGRADIENTElement {
	return e.DATASTAR_IGNORE_MORPHSet(true)
}

type SVGRadialGradientIndicatorMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientIndicatorModCase(
	s string,
) SVGRadialGradientIndicatorMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Creates a signal and sets its value to true while a fetch request is in flight,
// otherwise false
// The signal can be used to show a loading indicator.
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *SVGRADIALGRADIENTElement) DATASTAR_INDICATOR(expression string, modifiers ...SVGRadialGradientIndicatorMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-indicator"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientIndicatorMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a signal and sets its value to true while a fetch request is in flight,
// otherwise false
// The signal can be used to show a loading indicator.
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_INDICATOR(condition bool, expression string, modifiers ...SVGRadialGradientIndicatorMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_INDICATOR(expression, modifiers...)
	}
	return e
}

// Creates a signal and sets its value to true while a fetch request is in flight,
// otherwise false
// The signal can be used to show a loading indicator.
//
// See: https://data-star.dev/reference/attributes#data-indicator
// Remove the attribute DATASTAR_INDICATOR from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_INDICATORRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-indicator")

	return e
}

type SVGRadialGradientInitMod customDataKeyModifier

// Delay the event listener in milliseconds.
func SVGRadialGradientInitModDelayMs(
	d time.Duration,
) SVGRadialGradientInitMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func SVGRadialGradientInitModDelaySec(
	d time.Duration,
) SVGRadialGradientInitMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func SVGRadialGradientInitModViewTransition() SVGRadialGradientInitMod {
	return func() string {
		return "viewtransition"
	}
}

// Runs an expression when the attribute is initialized
// This can happen on page load, when an element is patched into the DOM, and any
// time the attribute is modified (via a backend action or otherwise).
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *SVGRADIALGRADIENTElement) DATASTAR_INIT(expression string, modifiers ...SVGRadialGradientInitMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-init"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientInitMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression when the attribute is initialized
// This can happen on page load, when an element is patched into the DOM, and any
// time the attribute is modified (via a backend action or otherwise).
//
// See: https://data-star.dev/reference/attributes#data-indicator
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_INIT(condition bool, expression string, modifiers ...SVGRadialGradientInitMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_INIT(expression, modifiers...)
	}
	return e
}

// Runs an expression when the attribute is initialized
// This can happen on page load, when an element is patched into the DOM, and any
// time the attribute is modified (via a backend action or otherwise).
//
// See: https://data-star.dev/reference/attributes#data-indicator
// Remove the attribute DATASTAR_INIT from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_INITRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-init")

	return e
}

type SVGRadialGradientJsonSignalsMod customDataKeyModifier

// Outputs a more compact JSON format without extra whitespace
// Useful for displaying filtered data inline.
func SVGRadialGradientJsonSignalsModTerse() SVGRadialGradientJsonSignalsMod {
	return func() string {
		return "terse"
	}
}

// Sets the text content of an element to a reactive JSON stringified version of
// signals
// Useful when troubleshooting an issue.
//
// See: https://data-star.dev/reference/attributes#data-json-signals
func (e *SVGRADIALGRADIENTElement) DATASTAR_JSON_SIGNALS(expression string, modifiers ...SVGRadialGradientJsonSignalsMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-json-signals"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientJsonSignalsMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Sets the text content of an element to a reactive JSON stringified version of
// signals
// Useful when troubleshooting an issue.
//
// See: https://data-star.dev/reference/attributes#data-json-signals
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_JSON_SIGNALS(condition bool, expression string, modifiers ...SVGRadialGradientJsonSignalsMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_JSON_SIGNALS(expression, modifiers...)
	}
	return e
}

// Sets the text content of an element to a reactive JSON stringified version of
// signals
// Useful when troubleshooting an issue.
//
// See: https://data-star.dev/reference/attributes#data-json-signals
// Remove the attribute DATASTAR_JSON_SIGNALS from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_JSON_SIGNALSRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-json-signals")

	return e
}

type SVGRadialGradientOnMod customDataKeyModifier

// Only run the expression once
// Only works with built-in events.
func SVGRadialGradientOnModOnce() SVGRadialGradientOnMod {
	return func() string {
		return "once"
	}
}

// Do not call preventDefault on the event listener
// Only works with built-in events.
func SVGRadialGradientOnModPassive() SVGRadialGradientOnMod {
	return func() string {
		return "passive"
	}
}

// Use capture event listener
// Only works with built-in events.
func SVGRadialGradientOnModCapture() SVGRadialGradientOnMod {
	return func() string {
		return "capture"
	}
}

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientOnModCase(
	s string,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Delay the event listener in milliseconds.
func SVGRadialGradientOnModDelayMs(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func SVGRadialGradientOnModDelaySec(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Debounces the event handler
func SVGRadialGradientOnModDebounceMs(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds with leading edge.
func SVGRadialGradientOnModDebounceMsLeading(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.leading", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds without trailing edge.
func SVGRadialGradientOnModDebounceMsNoTrailing(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.notrailing", d.Milliseconds())
	}
}

// Debounces the event handler
func SVGRadialGradientOnModDebounceSec(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds with leading edge.
func SVGRadialGradientOnModDebounceSecLeading(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.leading", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds without trailing edge.
func SVGRadialGradientOnModDebounceSecNoTrailing(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.notrailing", int(d.Seconds()))
	}
}

// Throttles the event handler
func SVGRadialGradientOnModThrottleMs(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds without leading edge.
func SVGRadialGradientOnModThrottleMsNoLeading(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.noleading", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds with trailing edge.
func SVGRadialGradientOnModThrottleMsTrailing(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.trailing", d.Milliseconds())
	}
}

// Throttles the event listener in seconds.
func SVGRadialGradientOnModThrottleSec(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds without leading edge.
func SVGRadialGradientOnModThrottleSecNoLeading(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.noleading", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds with trailing edge.
func SVGRadialGradientOnModThrottleSecTrailing(
	d time.Duration,
) SVGRadialGradientOnMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.trailing", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func SVGRadialGradientOnModViewTransition() SVGRadialGradientOnMod {
	return func() string {
		return "viewtransition"
	}
}

// Attaches the event listener to the 'window' element.
func SVGRadialGradientOnModWindow() SVGRadialGradientOnMod {
	return func() string {
		return "window"
	}
}

// Calls 'preventDefault' on the event listener.
func SVGRadialGradientOnModPrevent() SVGRadialGradientOnMod {
	return func() string {
		return "prevent"
	}
}

// Triggers when the event is outside the element.
func SVGRadialGradientOnModOutside() SVGRadialGradientOnMod {
	return func() string {
		return "outside"
	}
}

// Calls 'stopPropagation' on the event listener.
func SVGRadialGradientOnModStop() SVGRadialGradientOnMod {
	return func() string {
		return "stop"
	}
}

// Attaches an event listener to an element, executing an expression whenever the
// event is triggered.
//
// See: https://data-star.dev/reference/attributes#data-on
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON(key string, expression string, modifiers ...SVGRadialGradientOnMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-on%s", suffix)

	customMods := lo.Map(modifiers, func(m SVGRadialGradientOnMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Attaches an event listener to an element, executing an expression whenever the
// event is triggered.
//
// See: https://data-star.dev/reference/attributes#data-on
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_ON(condition bool, key string, expression string, modifiers ...SVGRadialGradientOnMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_ON(key, expression, modifiers...)
	}
	return e
}

// Attaches an event listener to an element, executing an expression whenever the
// event is triggered.
//
// See: https://data-star.dev/reference/attributes#data-on
// Remove the attribute DATASTAR_ON from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ONRemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-on" + suffix)

	return e
}

type SVGRadialGradientOnIntersectMod customDataKeyModifier

// Only run the expression once
// Only works with built-in events.
func SVGRadialGradientOnIntersectModOnce() SVGRadialGradientOnIntersectMod {
	return func() string {
		return "once"
	}
}

// Trigger when half of the element is visible.
func SVGRadialGradientOnIntersectModHalf() SVGRadialGradientOnIntersectMod {
	return func() string {
		return "half"
	}
}

// Trigger when the full element is visible.
func SVGRadialGradientOnIntersectModFull() SVGRadialGradientOnIntersectMod {
	return func() string {
		return "full"
	}
}

// Delay the event listener in milliseconds.
func SVGRadialGradientOnIntersectModDelayMs(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func SVGRadialGradientOnIntersectModDelaySec(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Debounces the event handler
func SVGRadialGradientOnIntersectModDebounceMs(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds with leading edge.
func SVGRadialGradientOnIntersectModDebounceMsLeading(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.leading", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds without trailing edge.
func SVGRadialGradientOnIntersectModDebounceMsNoTrailing(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.notrailing", d.Milliseconds())
	}
}

// Debounces the event handler
func SVGRadialGradientOnIntersectModDebounceSec(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds with leading edge.
func SVGRadialGradientOnIntersectModDebounceSecLeading(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.leading", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds without trailing edge.
func SVGRadialGradientOnIntersectModDebounceSecNoTrailing(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.notrailing", int(d.Seconds()))
	}
}

// Throttles the event handler
func SVGRadialGradientOnIntersectModThrottleMs(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds without leading edge.
func SVGRadialGradientOnIntersectModThrottleMsNoLeading(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.noleading", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds with trailing edge.
func SVGRadialGradientOnIntersectModThrottleMsTrailing(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.trailing", d.Milliseconds())
	}
}

// Throttles the event listener in seconds.
func SVGRadialGradientOnIntersectModThrottleSec(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds without leading edge.
func SVGRadialGradientOnIntersectModThrottleSecNoLeading(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.noleading", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds with trailing edge.
func SVGRadialGradientOnIntersectModThrottleSecTrailing(
	d time.Duration,
) SVGRadialGradientOnIntersectMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.trailing", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func SVGRadialGradientOnIntersectModViewTransition() SVGRadialGradientOnIntersectMod {
	return func() string {
		return "viewtransition"
	}
}

// Runs an expression when the element intersects with the viewport.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_INTERSECT(expression string, modifiers ...SVGRadialGradientOnIntersectMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-intersect"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientOnIntersectMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression when the element intersects with the viewport.
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_ON_INTERSECT(condition bool, expression string, modifiers ...SVGRadialGradientOnIntersectMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_ON_INTERSECT(expression, modifiers...)
	}
	return e
}

// Runs an expression when the element intersects with the viewport.
// Remove the attribute DATASTAR_ON_INTERSECT from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_INTERSECTRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-intersect")

	return e
}

type SVGRadialGradientOnIntervalMod customDataKeyModifier

// Sets the interval duration in milliseconds.
func SVGRadialGradientOnIntervalModDurationMs(
	d time.Duration,
) SVGRadialGradientOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%dms", d.Milliseconds())
	}
}

// Sets the interval duration in milliseconds
// Execute the first interval immediately.
func SVGRadialGradientOnIntervalModDurationMsLeading(
	d time.Duration,
) SVGRadialGradientOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%dms.leading", d.Milliseconds())
	}
}

// Sets the interval duration in seconds.
func SVGRadialGradientOnIntervalModDurationSec(
	d time.Duration,
) SVGRadialGradientOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%ds", int(d.Seconds()))
	}
}

// Sets the interval duration in seconds
// Execute the first interval immediately.
func SVGRadialGradientOnIntervalModDurationSecLeading(
	d time.Duration,
) SVGRadialGradientOnIntervalMod {
	return func() string {
		return fmt.Sprintf("duration.%ds.leading", int(d.Seconds()))
	}
}

// Wraps the expression in 'document.startViewTransition()' when the View
// Transition API is available.
func SVGRadialGradientOnIntervalModViewTransition() SVGRadialGradientOnIntervalMod {
	return func() string {
		return "viewtransition"
	}
}

// Runs an expression at a regular interval
// The interval duration defaults to one second and can be modified using the
// '__duration' modifier.
//
// See: https://data-star.dev/reference/attributes#data-on-interval
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_INTERVAL(expression string, modifiers ...SVGRadialGradientOnIntervalMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-interval"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientOnIntervalMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression at a regular interval
// The interval duration defaults to one second and can be modified using the
// '__duration' modifier.
//
// See: https://data-star.dev/reference/attributes#data-on-interval
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_ON_INTERVAL(condition bool, expression string, modifiers ...SVGRadialGradientOnIntervalMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_ON_INTERVAL(expression, modifiers...)
	}
	return e
}

// Runs an expression at a regular interval
// The interval duration defaults to one second and can be modified using the
// '__duration' modifier.
//
// See: https://data-star.dev/reference/attributes#data-on-interval
// Remove the attribute DATASTAR_ON_INTERVAL from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_INTERVALRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-interval")

	return e
}

type SVGRadialGradientOnSignalPatchMod customDataKeyModifier

// Delay the event listener in milliseconds.
func SVGRadialGradientOnSignalPatchModDelayMs(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("delay.%dms", d.Milliseconds())
	}
}

// Delay the event listener in seconds.
func SVGRadialGradientOnSignalPatchModDelaySec(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("delay.%ds", int(d.Seconds()))
	}
}

// Debounces the event handler
func SVGRadialGradientOnSignalPatchModDebounceMs(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds with leading edge.
func SVGRadialGradientOnSignalPatchModDebounceMsLeading(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.leading", d.Milliseconds())
	}
}

// Debounce the event listener in milliseconds without trailing edge.
func SVGRadialGradientOnSignalPatchModDebounceMsNoTrailing(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%dms.notrailing", d.Milliseconds())
	}
}

// Debounces the event handler
func SVGRadialGradientOnSignalPatchModDebounceSec(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds with leading edge.
func SVGRadialGradientOnSignalPatchModDebounceSecLeading(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.leading", int(d.Seconds()))
	}
}

// Debounce the event listener in seconds without trailing edge.
func SVGRadialGradientOnSignalPatchModDebounceSecNoTrailing(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("debounce.%ds.notrailing", int(d.Seconds()))
	}
}

// Throttles the event handler
func SVGRadialGradientOnSignalPatchModThrottleMs(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds without leading edge.
func SVGRadialGradientOnSignalPatchModThrottleMsNoLeading(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.noleading", d.Milliseconds())
	}
}

// Throttle the event listener in milliseconds with trailing edge.
func SVGRadialGradientOnSignalPatchModThrottleMsTrailing(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%dms.trailing", d.Milliseconds())
	}
}

// Throttles the event listener in seconds.
func SVGRadialGradientOnSignalPatchModThrottleSec(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds without leading edge.
func SVGRadialGradientOnSignalPatchModThrottleSecNoLeading(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.noleading", int(d.Seconds()))
	}
}

// Throttle the event listener in seconds with trailing edge.
func SVGRadialGradientOnSignalPatchModThrottleSecTrailing(
	d time.Duration,
) SVGRadialGradientOnSignalPatchMod {
	return func() string {
		return fmt.Sprintf("throttle.%ds.trailing", int(d.Seconds()))
	}
}

// Runs an expression whenever any signals are patched
// This is useful for tracking changes, updating computed values, or triggering
// side effects when data updates.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_SIGNAL_PATCH(expression string, modifiers ...SVGRadialGradientOnSignalPatchMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-signal-patch"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientOnSignalPatchMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Runs an expression whenever any signals are patched
// This is useful for tracking changes, updating computed values, or triggering
// side effects when data updates.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_ON_SIGNAL_PATCH(condition bool, expression string, modifiers ...SVGRadialGradientOnSignalPatchMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_ON_SIGNAL_PATCH(expression, modifiers...)
	}
	return e
}

// Runs an expression whenever any signals are patched
// This is useful for tracking changes, updating computed values, or triggering
// side effects when data updates.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch
// Remove the attribute DATASTAR_ON_SIGNAL_PATCH from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_SIGNAL_PATCHRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-signal-patch")

	return e
}

// Filters which signals to watch when using the data-on-signal-patch attribute.
//
// The data-on-signal-patch-filter attribute accepts an object with include and/or
// exclude properties that are regular expressions.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch-filter
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_SIGNAL_PATCH_FILTER(expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-on-signal-patch-filter"

	e.StringAttributes.Set(key, expression)
	return e
}

// Filters which signals to watch when using the data-on-signal-patch attribute.
//
// The data-on-signal-patch-filter attribute accepts an object with include and/or
// exclude properties that are regular expressions.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch-filter
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_ON_SIGNAL_PATCH_FILTER(condition bool, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_ON_SIGNAL_PATCH_FILTER(expression)
	}
	return e
}

// Filters which signals to watch when using the data-on-signal-patch attribute.
//
// The data-on-signal-patch-filter attribute accepts an object with include and/or
// exclude properties that are regular expressions.
//
// See: https://data-star.dev/reference/attributes#data-on-signal-patch-filter
// Remove the attribute DATASTAR_ON_SIGNAL_PATCH_FILTER from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_ON_SIGNAL_PATCH_FILTERRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-on-signal-patch-filter")

	return e
}

// Preserves the value of an attribute when morphing DOM elements.
//
// See: https://data-star.dev/reference/attributes#data-preserve-attr
func (e *SVGRADIALGRADIENTElement) DATASTAR_PRESERVE_ATTR(expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-preserve-attr"

	e.StringAttributes.Set(key, expression)
	return e
}

// Preserves the value of an attribute when morphing DOM elements.
//
// See: https://data-star.dev/reference/attributes#data-preserve-attr
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_PRESERVE_ATTR(condition bool, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_PRESERVE_ATTR(expression)
	}
	return e
}

// Preserves the value of an attribute when morphing DOM elements.
//
// See: https://data-star.dev/reference/attributes#data-preserve-attr
// Remove the attribute DATASTAR_PRESERVE_ATTR from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_PRESERVE_ATTRRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-preserve-attr")

	return e
}

type SVGRadialGradientRefMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientRefModCase(
	s string,
) SVGRadialGradientRefMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Creates a new signal that is a reference to the element on which the data
// attribute is placed.
//
// See: https://data-star.dev/reference/attributes#data-ref
func (e *SVGRADIALGRADIENTElement) DATASTAR_REF(expression string, modifiers ...SVGRadialGradientRefMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-ref"

	customMods := lo.Map(modifiers, func(m SVGRadialGradientRefMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Creates a new signal that is a reference to the element on which the data
// attribute is placed.
//
// See: https://data-star.dev/reference/attributes#data-ref
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_REF(condition bool, expression string, modifiers ...SVGRadialGradientRefMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_REF(expression, modifiers...)
	}
	return e
}

// Creates a new signal that is a reference to the element on which the data
// attribute is placed.
//
// See: https://data-star.dev/reference/attributes#data-ref
// Remove the attribute DATASTAR_REF from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_REFRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-ref")

	return e
}

// Shows or hides an element based on whether an expression evaluates to 'true' or
// 'false'
// For anything with custom requirements, use 'data-class' instead.
//
// See: https://data-star.dev/reference/attributes#data-show
func (e *SVGRADIALGRADIENTElement) DATASTAR_SHOW(expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-show"

	e.StringAttributes.Set(key, expression)
	return e
}

// Shows or hides an element based on whether an expression evaluates to 'true' or
// 'false'
// For anything with custom requirements, use 'data-class' instead.
//
// See: https://data-star.dev/reference/attributes#data-show
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_SHOW(condition bool, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_SHOW(expression)
	}
	return e
}

// Shows or hides an element based on whether an expression evaluates to 'true' or
// 'false'
// For anything with custom requirements, use 'data-class' instead.
//
// See: https://data-star.dev/reference/attributes#data-show
// Remove the attribute DATASTAR_SHOW from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_SHOWRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-show")

	return e
}

type SVGRadialGradientSignalsMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientSignalsModCase(
	s string,
) SVGRadialGradientSignalsMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Only patches signals if their keys do not already exist
// This is useful for setting defaults without overwriting existing values.
func SVGRadialGradientSignalsModIfMissing() SVGRadialGradientSignalsMod {
	return func() string {
		return "ifmissing"
	}
}

// Patches (adds, updates or removes) one or more signals into the existing
// signals
// Values defined later in the DOM tree override those defined earlier.
//
// See: https://data-star.dev/reference/attributes#data-signals
func (e *SVGRADIALGRADIENTElement) DATASTAR_SIGNALS(key string, expression string, modifiers ...SVGRadialGradientSignalsMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-signals%s", suffix)

	customMods := lo.Map(modifiers, func(m SVGRadialGradientSignalsMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Patches (adds, updates or removes) one or more signals into the existing
// signals
// Values defined later in the DOM tree override those defined earlier.
//
// See: https://data-star.dev/reference/attributes#data-signals
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_SIGNALS(condition bool, key string, expression string, modifiers ...SVGRadialGradientSignalsMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_SIGNALS(key, expression, modifiers...)
	}
	return e
}

// Patches (adds, updates or removes) one or more signals into the existing
// signals
// Values defined later in the DOM tree override those defined earlier.
//
// See: https://data-star.dev/reference/attributes#data-signals
// Remove the attribute DATASTAR_SIGNALS from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_SIGNALSRemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-signals" + suffix)

	return e
}

type SVGRadialGradientStyleMod customDataKeyModifier

// Converts the casing of the signal name.
//   - 'camel' – Camel case: 'mySignal' (default)
//   - 'kebab' – Kebab case: 'my-signal'
//   - 'snake' – Snake case: 'my_signal'
//   - 'pascal' – Pascal case: 'MySignal'
func SVGRadialGradientStyleModCase(
	s string,
) SVGRadialGradientStyleMod {
	return func() string {
		return fmt.Sprintf("case.%s", s)
	}
}

// Sets the value of inline CSS styles on an element based on an expression, and
// keeps them in sync.
//
// See: https://data-star.dev/reference/attributes#data-style
func (e *SVGRADIALGRADIENTElement) DATASTAR_STYLE(key string, expression string, modifiers ...SVGRadialGradientStyleMod) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	key = fmt.Sprintf("data-style%s", suffix)

	customMods := lo.Map(modifiers, func(m SVGRadialGradientStyleMod, i int) customDataKeyModifier {
		return customDataKeyModifier(m)
	})
	key = customDataKey(key, customMods...)
	e.StringAttributes.Set(key, expression)
	return e
}

// Sets the value of inline CSS styles on an element based on an expression, and
// keeps them in sync.
//
// See: https://data-star.dev/reference/attributes#data-style
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_STYLE(condition bool, key string, expression string, modifiers ...SVGRadialGradientStyleMod) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_STYLE(key, expression, modifiers...)
	}
	return e
}

// Sets the value of inline CSS styles on an element based on an expression, and
// keeps them in sync.
//
// See: https://data-star.dev/reference/attributes#data-style
// Remove the attribute DATASTAR_STYLE from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_STYLERemove(key string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	suffix := key
	if suffix != "" {
		suffix = ":" + suffix
	}
	e.StringAttributes.Del("data-style" + suffix)

	return e
}

// Binds the text content of an element to an expression.
//
// See: https://data-star.dev/reference/attributes#data-text
func (e *SVGRADIALGRADIENTElement) DATASTAR_TEXT(expression string) *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}

	key := "data-text"

	e.StringAttributes.Set(key, expression)
	return e
}

// Binds the text content of an element to an expression.
//
// See: https://data-star.dev/reference/attributes#data-text
func (e *SVGRADIALGRADIENTElement) IfDATASTAR_TEXT(condition bool, expression string) *SVGRADIALGRADIENTElement {
	if condition {
		e.DATASTAR_TEXT(expression)
	}
	return e
}

// Binds the text content of an element to an expression.
//
// See: https://data-star.dev/reference/attributes#data-text
// Remove the attribute DATASTAR_TEXT from the element.
func (e *SVGRADIALGRADIENTElement) DATASTAR_TEXTRemove() *SVGRADIALGRADIENTElement {
	if e.StringAttributes == nil {
		return e
	}

	e.StringAttributes.Del("data-text")

	return e
}
